### ISSUE TITLE
Help With Tweaking The Default Minimal Mistakes Layout

### ISSUE THREAD

**Issue by nsubordin81** [excellalabs/blog-in-a-box#90] opened 2023-05-12 22:11 UTC
### tools: 
Chrome Version 113.0.5672.93 (Official Build) (64-bit)
VS Code
blog-in-a-box based project with no significant changes, only typical customization of _config.yaml and the below added files for stylesheets

existing: 
![image](https://github.com/excellalabs/blog-in-a-box/assets/4014893/0a65ee95-60ab-4723-acda-8db943f4da11)

desired:
![image](https://github.com/excellalabs/blog-in-a-box/assets/4014893/01211741-2280-43dd-9f97-702aa8e12d02)

I was able to achieve the above using the modification to the css pictured in the 'desired' image. the new portion added to the .archive class was `padding 0 3rem !important;` 

## what I've tried so far: 
reading through this guide https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/ and attempting to follow the instructions under "Customizing" section. I tried creating a copy of main.scss first and then saw this note:

```
*Note*: To make more extensive changes and customize the Sass partials bundled in the gem. You will need to copy the complete contents of the _sass directory to <your_project> due to the way Jekyll currently reads those files.
```
since for this particular change I want to be modifying the .archive class and that has its own partial, I expect I needed to copy over the whole _sass/ directory. Here is a screenshot of my vscode project explorer, to show what I have done to structure the directories within my project: 

![image](https://github.com/excellalabs/blog-in-a-box/assets/4014893/f3c43bf7-838b-4f65-8a2b-a8c1674cb82e)

  So I'm doing this now. in the _sass/_archive.scss partial, I have added that padding line:

```css
.archive {
  margin-top: 1em;
  margin-bottom: 2em;
  padding 0 3rem !important;

  @include breakpoint($large) {
    float: right;
    width: calc(100% - #{$right-sidebar-width-narrow});
    padding-right: $right-sidebar-width-narrow;
  }

  @include breakpoint($x-large) {
    width: calc(100% - #{$right-sidebar-width});
    padding-right: $right-sidebar-width;
  }
}
```

but when I am doing `localdev` I am not seeing this style show up when I inspect the page with chrome dev tools.

**Comment by SeanKilleen** [comment] 2023-05-13 03:33
I figured it out.

Minimal mistakes is assuming you're operating from the root of the repository. But one trade-off we had to make for GitHub pages is that everything in blog-in-the-box is in the docs subfolder.

So, your overrides weren't overriding because the file wasn't in the right spot.

Submitted https://github.com/nsubordin81/blog.synapseflux.com/pull/3, which should fix the problem. We can close this once that's confirmed (though my local preview showed the change as expected)

**Comment by nsubordin81** [comment] 2023-05-14 01:55
Oh that makes total sense! Wow good catch, thank you thank you thank you! That not only solves this particular change but now I can override anything in the way the theme describes. Sa-weet. Going to approve and merge the pr before closing this out, probably tomorrow or Monday, doing all this typing on my 🤳

**Closed as completed** 2023-05-15 14:53 UTC
